pipeline {
  agent{
    docker{
      image 'maven:3.6.1-jdk-8-slim'
      args '-v $HOME/.m2:/root/.m2'
    }
  }

  stages{
    
    stage("build"){
      when{
         changeset "**/worker/**"
      }
      steps{
        echo 'Compiling worker app'
        dir('worker'){
          sh 'mvn compile'
        }
      }
    }
    
    stage("test"){
      when{
         changeset "**/worker/**"
      }
      steps{
        echo 'Running Unit Test on worker app'
        dir('worker'){
          sh 'mvn clean test'
        }
      }
    }
    
    stage("package"){
      when{
        branch 'master'
        changeset "**/worker/**"
      }
      steps{
        echo 'Packaging worker app'
        dir('worker'){
          sh 'mvn package -DskipTests'
        }
      }
    }
    
  }
  
  post{        
      success {
        slackSend (channel: "instavote", message: "ilham - Build Succeeded - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
      }
      failure {
        slackSend (channel: "instavote", message: "ilham - Build Failed - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
      }
      always{
        echo 'Building multibranch pipeline for worker is completed..'
      }
  }
}



